### ISSUE TITLE
Exception when opening file

### ISSUE THREAD

**Issue by JFronny** [manifold-systems/manifold-ij#13]
When opening a file in Idea Ultimate 2022.2.2 with the Manifold plugin 2022.1.21, the following exception gets thrown
```
java.lang.InternalError: java.lang.IllegalAccessException: static final field has no write access: com.intellij.psi.impl.java.stubs.JavaStubElementTypes.LITERAL_EXPRESSION/com.intellij.psi.impl.java.stubs.JavaLiteralExpressionElementType/putStatic, from class java.lang.Object (module java.base)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:167)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:176)
	at java.base/java.lang.reflect.Field.acquireOverrideFieldAccessor(Field.java:1184)
	at java.base/java.lang.reflect.Field.getOverrideFieldAccessor(Field.java:1153)
	at java.base/java.lang.reflect.Field.set(Field.java:820)
	at manifold.util.ReflectUtil.setFinal(ReflectUtil.java:1274)
	at manifold.util.ReflectUtil.setFinal(ReflectUtil.java:1261)
	at manifold.util.ReflectUtil.access$400(ReflectUtil.java:56)
	at manifold.util.ReflectUtil$FieldRef.setStatic(ReflectUtil.java:1025)
	at manifold.ij.core.ManApplicationLoadListener.overrideJavaStringLiterals(ManApplicationLoadListener.java:164)
	at manifold.ij.core.ManApplicationLoadListener.overrideJavaParserStuff(ManApplicationLoadListener.java:87)
	at manifold.ij.core.ManApplicationLoadListener.beforeApplicationLoaded(ManApplicationLoadListener.java:67)
	at com.intellij.idea.ApplicationLoader.initConfigurationStore(ApplicationLoader.kt:431)
	at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt:156)
	at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1163)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.intellij.idea.ApplicationLoader$initApplication$block$2.execute(ApplicationLoader.kt:142)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1147)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1163)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalAccessException: static final field has no write access: com.intellij.psi.impl.java.stubs.JavaStubElementTypes.LITERAL_EXPRESSION/com.intellij.psi.impl.java.stubs.JavaLiteralExpressionElementType/putStatic, from class java.lang.Object (module java.base)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:955)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectField(MethodHandles.java:3494)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectSetter(MethodHandles.java:3485)
	at java.base/java.lang.invoke.MethodHandleImpl$1.unreflectField(MethodHandleImpl.java:1637)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:145)
	... 31 more
```

**Comment by rsmckinney** [comment]
@JFronny Thanks for submitting this, a new manifold plugin release is pending approval at jetbrains that addresses several issues, will be available by eod Monday
